version: '3'

services:
  mysql:
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - wordpress-network
    container_name: db-container

  wordpress:
    build:
      context: ./wordpress
    ports:
      - "8080:80"
    networks:
      - wordpress-network
    container_name: wordpress-container
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: db-container
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

networks:
  wordpress-network:

volumes:
  mysql-data:
