# Use the official WordPress image as the base image
FROM wordpress:latest

# Environment variables for WordPress
ENV WORDPRESS_DB_HOST=db-container
ENV WORDPRESS_DB_NAME=wordpress
ENV WORDPRESS_DB_USER=wordpress
ENV WORDPRESS_DB_PASSWORD=wordpress
